# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CovidHelper' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for CovidHelper
  pod 'Stripe'
  pod 'Alamofire'
  pod 'FirebaseUI/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'SwiftyJSON'
  pod 'Firebase'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'

end
